"use client";

import { ReactNode, useEffect, useState } from "react";
import { SatsWagmiConfig } from "@gobob/sats-wagmi";
import { Metadata } from "next";

interface LayoutProps {
  children: ReactNode;
  // You can add more props as needed
}

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

function Layout({ children }: LayoutProps) {
  const [isClient, setIsClient] = useState(false);

  useEffect(() => {
    if (typeof window !== "undefined") {
      setIsClient(true);
    }
  }, []);

  return <div>{isClient ? <SatsWagmiConfig network="testnet">{children}</SatsWagmiConfig> : <>{children}</>}</div>;
}

export default Layout;
