version: '3'

volumes:
  backend-static:

services:
  bob:
    restart: always
    build: .
    image: bob_backend
    env_file: .env
    ports:
      - "8002:8002"
    command: gunicorn -w 10 bob.wsgi:application -b :8002 -t 9999
    volumes:
      - .:/bob2
      - backend-static:/bob2/static

  nginx:
    restart: always
    build: ./nginx/
    image: bob_backend_nginx
    ports:
      - "8084:8084"
    volumes:
      - backend-static:/var/www/bob/static
    depends_on:
      - bob
