version: '3'

volumes:
  backend-static:

services:
  redis:
    image: "redis:alpine"
  bob:
    restart: always
    build: .
    image: bob_backend
    env_file: .env
    ports:
      - "8002:8006"
    command: gunicorn -w 10 bob.wsgi:application -b :8006 -t 9999
    volumes:
      - .:/bob
      - backend-static:/bob/static
    depends_on:
      - redis
  celery:
    build: .
    container_name: bob_celery_worker
    command: celery worker -A bob --loglevel=debug --concurrency=4
    volumes:
      - .:/bob
    depends_on:
      - redis
      - bob
  celery-beat:
    build: .
    container_name: bob_celery_beat
    environment:
        CELERY_BROKER_URL: 'redis://redis:6379'
    command: celery -A bob beat --loglevel=debug --scheduler=django_celery_beat.schedulers:DatabaseScheduler
    volumes:
      - .:/bob
    depends_on:
      - redis
      - bob

  nginx:
    restart: always
    build: ./nginx/
    image: bob_backend_nginx
    ports:
      - "8084:8084"
    volumes:
      - backend-static:/var/www/bob/static
    depends_on:
      - bob
